### ISSUE TITLE
Get Multi-gpu training running

### ISSUE THREAD

**Issue by GabrielKP** [DFKI-NLP/sherlock#32]
I am having issues getting multi-gpu running. Am I missing out on something?

My command:
```
usrun_cuda21_pt_1.10.sh -p RTXA6000 --gpus=2 ./run.sh python ./scripts/run_ner.py --model_type bert   --model_name_or_path bert-base-uncased   --do_train   --do_eval   --do_predict   --evaluate_during_training   --eval_all_checkpoints   --do_lower_case   --data_dir /ds/text/tacred/data/json/  --save_steps 8500   --logging_steps 8500   --max_seq_length 128   --per_gpu_eval_batch_size=8   --per_gpu_train_batch_size=8   --learning_rate 2e-5   --num_train_epochs 5.0   --overwrite_cache   --overwrite_output_dir   --output_dir /netscratch/kressin/experiments/sherlock/ 
```
I also have tried with `--fp16` but it does not help. Same error.

Error:
```
Traceback (most recent call last):
  File "./scripts/run_ner.py", line 782, in <module>
    main()
  File "./scripts/run_ner.py", line 693, in main
    global_step, tr_loss = train(args, dataset_reader, converter, model, tokenizer)
  File "./scripts/run_ner.py", line 191, in train
    outputs = model(**batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_bert.py", line 1365, in forward
    outputs = self.bert(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_bert.py", line 734, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
StopIteration

srun: error: serv-9219: task 0: Exited with exit code 1
```

**Comment by GabrielKP** [comment]
I tested with Ubuntu 20 and 21, I will try to test with 19 and an even older cuda version next week.

**Comment by GabrielKP** [comment]
This problem is now on a new scale:
the current allennlp implementation #8 does not support multi-gpu handling. A proper multi-gpu config file could solve that problem, but maybe the [DatasetReader](sherlock/allennlp/sherlock_dataset_reader.py) will need adaptions.
